In [1]:
def step_func_one_variable(x):
    if x>0:
        return 1
    else:
        return 0

In [2]:
import numpy as np

In [3]:
step_func=np.vectorize(step_func_one_variable)
step_func(np.array([-1,0,2]))

array([0, 0, 1])

In [4]:
W_1=np.array(([0,1,2],
                    [3,4,5],
                    [6,7,8]),'float64')

In [5]:
b_1=np.array([4/15,-85/30,-59/15]).reshape((3,1))
b_1

array([[ 0.26666667],
       [-2.83333333],
       [-3.93333333]])

In [6]:
x=np.array([1/2,1/3,1/5]).reshape((3,1))
x

array([[ 0.5       ],
       [ 0.33333333],
       [ 0.2       ]])

In [12]:
z_1=W_1.dot(x)+b_1
z_1

array([[ 1.],
       [ 1.],
       [ 3.]])

In [13]:
y_1=step_func(z_1)
y_1

array([[1],
       [1],
       [1]])

In [15]:
W_2=np.array(([-3,-2,-1],
                    [0,0,0],
                    [-5,0,3]),'float64')

In [16]:
b_2=np.array([4,1,1]).reshape(3,1)
b_2

array([[4],
       [1],
       [1]])

In [17]:
W_2@y_1+b_2

array([[-2.],
       [ 1.],
       [-1.]])

In [19]:
step_func(W_2@y_1+b_2)

array([[0],
       [1],
       [0]])