# gauss method with pivot swap

In [43]:
import numpy as np

In [44]:
a=np.matrix([[0,1,2],
                        [1,0,3],
                        [3,1,0]],dtype='float64')


In [45]:
b=np.matrix([2,2,-3]).T
b

matrix([[ 2],
        [ 2],
        [-3]])

In [46]:
a=np.concatenate([a,b],axis=1)
a

matrix([[ 0.,  1.,  2.,  2.],
        [ 1.,  0.,  3.,  2.],
        [ 3.,  1.,  0., -3.]])

In [47]:
row=0
maxind=np.argmax(abs(a[row:,0]))
maxind

2

In [48]:
#swap 
a[[row,maxind],:]=a[[maxind,row],:]
a

matrix([[ 3.,  1.,  0., -3.],
        [ 1.,  0.,  3.,  2.],
        [ 0.,  1.,  2.,  2.]])

# do gauss for row=0

In [49]:
for i in range(1,a.shape[0]):
    p= a[i,0] /a[0,0]
    a[i]-=p*a[0]
a

matrix([[ 3.        ,  1.        ,  0.        , -3.        ],
        [ 0.        , -0.33333333,  3.        ,  3.        ],
        [ 0.        ,  1.        ,  2.        ,  2.        ]])

In [52]:
row=1
maxind=np.argmax(abs(a[row:,1]))+row
maxind

2

In [53]:
#swap 
a[[row,maxind],:]=a[[maxind,row],:]
a

matrix([[ 3.        ,  1.        ,  0.        , -3.        ],
        [ 0.        ,  1.        ,  2.        ,  2.        ],
        [ 0.        , -0.33333333,  3.        ,  3.        ]])

In [79]:
a=np.matrix([[0,1,2],
                        [1,0,3],
                        [3,1,0]],dtype='float64')
b=np.matrix([2,2,-3],dtype='float64').T
x=np.matrix([None,None,None],dtype='float64').T

a=np.concatenate([a,b],axis=1)

#push forward
(row,col)=a.shape
for j in range(row):
    maxind=np.argmax(abs(a[j:,j]))+j
    a[[j,maxind],:]=a[[maxind,j],:]
    for i in range(j+1,row):
        p= a[i,j] /a[j,j]
        a[i]-=p*a[j]
print(a)
#back forward
for i in range(row)[::-1]:
    x[i]=(a[i,col-1]-np.dot(a[i,i+1:row],x[i+1:row]))/a[i,i]
print(x)
print("check that ax=b")
a=np.matrix([[0,1,2],
                        [1,0,3],
                        [3,1,0]],dtype='float64')
b=np.matrix([2,2,-3],dtype='float64').T
print(a)
print(b)
print(a @ x - b)

[[ 3.          1.          0.         -3.        ]
 [ 0.          1.          2.          2.        ]
 [ 0.          0.          3.66666667  3.66666667]]
[[-1.]
 [ 0.]
 [ 1.]]
check that ax=b
[[ 0.  1.  2.]
 [ 1.  0.  3.]
 [ 3.  1.  0.]]
[[ 2.]
 [ 2.]
 [-3.]]
[[ 0.]
 [ 0.]
 [ 0.]]


3.6666666666666665