# solve linear equation


In [1]:
import numpy as np

In [2]:
a=np.matrix([[2,4,6],
                        [1,-1,5],
                        [4,1,-2]],dtype='f')
a

matrix([[ 2.,  4.,  6.],
        [ 1., -1.,  5.],
        [ 4.,  1., -2.]], dtype=float32)

In [3]:
b=np.matrix([28,7,21],'f').T
b

matrix([[ 28.],
        [  7.],
        [ 21.]], dtype=float32)

In [4]:
x=np.matrix([5,3,1],dtype='f').T
x

matrix([[ 5.],
        [ 3.],
        [ 1.]], dtype=float32)

# check that $ax=b$

In [5]:
a @ x - b

matrix([[ 0.],
        [ 0.],
        [ 0.]], dtype=float32)

# solve linear equation using Gauss mehtod

# 0 列目を消去

In [6]:
p=a[1,0]/a[0,0]
p

0.5

In [7]:
a[1]-=p*a[0]
a

matrix([[ 2.,  4.,  6.],
        [ 0., -3.,  2.],
        [ 4.,  1., -2.]], dtype=float32)

In [8]:
p=a[2,0]/a[0,0]
a[2]-=p*a[0]
a

matrix([[  2.,   4.,   6.],
        [  0.,  -3.,   2.],
        [  0.,  -7., -14.]], dtype=float32)

In [9]:
a.shape

(3, 3)

# for 文で　0列目消去を自動化

In [10]:
a=np.matrix([[2,4,6],
                        [1,-1,5],
                        [4,1,-2]],dtype='f')

for i in range(1,a.shape[0]):
    p= a[i,0] /a[0,0]
    a[i]-=p*a[0]
a

matrix([[  2.,   4.,   6.],
        [  0.,  -3.,   2.],
        [  0.,  -7., -14.]], dtype=float32)

# 1列目を消去

In [11]:
p=a[2,1]/a[1,1]
a[2]-=p*a[1]
a

matrix([[  2.        ,   4.        ,   6.        ],
        [  0.        ,  -3.        ,   2.        ],
        [  0.        ,   0.        , -18.66666603]], dtype=float32)

 # 今までの操作を for 文で一般化

In [12]:
a=np.matrix([[2,4,6],
             [1,-1,5],
             [4,1,-2]],dtype='f')

for j in range(a.shape[1]):
    for i in range(j+1,a.shape[0]):
        p= a[i,j] /a[j,j]
        a[i]-=p*a[j]
a


matrix([[  2.        ,   4.        ,   6.        ],
        [  0.        ,  -3.        ,   2.        ],
        [  0.        ,   0.        , -18.66666603]], dtype=float32)

# $b$ の操作を忘れていたので係数拡大行列にまとめて gauss 消去法を適用することにする．

In [13]:
a=np.matrix([[2,4,6],
                        [1,-1,5],
                        [4,1,-2]],dtype='f')

b=np.matrix([28,7,21],'f').T

ext_a=np.concatenate([a,b],axis=1)
ext_a

matrix([[  2.,   4.,   6.,  28.],
        [  1.,  -1.,   5.,   7.],
        [  4.,   1.,  -2.,  21.]], dtype=float32)

In [14]:
n=ext_a.shape[0]
a=ext_a
for j in range(n):
    for i in range(j+1,n):
        p= a[i,j] /a[j,j]
        a[i]-=p*a[j]
a

matrix([[  2.        ,   4.        ,   6.        ,  28.        ],
        [  0.        ,  -3.        ,   2.        ,  -7.        ],
        [  0.        ,   0.        , -18.66666603, -18.66666794]], dtype=float32)

# back forward

In [15]:
row=a.shape[0]
x[2]=a[2,3]/a[2,2]
print(x[2])
x2=(a[2,3]-np.dot(a[2,3:row],x[3:row]))/a[2,2]
x2

[[ 1.00000012]]


matrix([[ 1.00000012]], dtype=float32)

In [16]:
row=a.shape[0]
x[1]=(a[1,3]-a[1,2]*x[2])/a[1,1]
print(x[1])
x1   =(a[1,3]-np.dot(a[1,2:row],x[2:row]))/a[1,1]
x1

[[ 3.]]


matrix([[ 3.]], dtype=float32)

In [17]:
row=a.shape[0]
x[0]=(a[0,3]-a[0,1]*x[1]-a[0,2]*x[2])/a[0,0]
print(x[0])
x0    =  (a[0,3]-np.dot(a[0,1:row],x[1:row]))/a[0,0]
print(x0)

[[ 4.99999952]]
[[ 5.]]


# for 文で一般化

In [18]:
a=np.matrix([[2,4,6],
                        [1,-1,5],
                        [4,1,-2]],dtype='f')

b=np.matrix([28,7,21],'f').T
x=np.empty(3).T

a=np.concatenate([a,b],axis=1)
#push forward
(row,col)=a.shape

for j in range(row):
    for i in range(j+1,row):
        p= a[i,j] /a[j,j]
        a[i]-=p*a[j]

#back forward

for i in range(row)[::-1]:
    x[i]=(a[i,col-1]-np.dot(a[i,i+1:row],x[i+1:row]))/a[i,i]

print(a)
print(x)


[[  2.           4.           6.          28.        ]
 [  0.          -3.           2.          -7.        ]
 [  0.           0.         -18.66666603 -18.66666794]]
[ 4.99999956  3.00000007  1.0000001 ]


In [19]:
print(a)
a[0,1:3]

[[  2.           4.           6.          28.        ]
 [  0.          -3.           2.          -7.        ]
 [  0.           0.         -18.66666603 -18.66666794]]


matrix([[ 4.,  6.]], dtype=float32)

In [20]:
print(a[0,1:a.shape[1]-1])
print(x[1:a.shape[1]-1])
np.dot(a[0,1:a.shape[1]-1],x[1:a.shape[1]-1])

[[ 4.  6.]]
[ 3.00000007  1.0000001 ]


matrix([[ 18.00000089]])