# jacobi method

In [68]:
import numpy as np

In [69]:
n=10
a=np.diag([5.]*n)
a+=np.diagflat([2.]*(n-1),1)
a+=np.diagflat([2.]*(n-1),-1)
print(a)

[[ 5.  2.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  5.  2.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  2.  5.  2.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  2.  5.  2.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  5.  2.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  2.  5.  2.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  2.  5.  2.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  2.  5.  2.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  2.  5.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  2.  5.]]


In [70]:
b=np.array([3,1,4,0,5,-1,6,-2,7,-15],dtype='f').T
#init x
x=np.ones(10).T

In [71]:
D=np.diag(np.diag(a))
L=np.tril(a,-1)
U=np.triu(a,+1)

In [72]:
invD=np.linalg.inv(D)

In [73]:
x_new=invD @ (b-(L+U) @ x)
x_new

array([ 0.2, -0.6,  0. , -0.8,  0.2, -1. ,  0.4, -1.2,  0.6, -3.4])

In [74]:
epsilon=0.0001
maxiteration=100

for k in range(maxiteration):
    x_new=invD @ (b-(L+U) @ x)
    if(np.linalg.norm(x_new-x) <epsilon):
        break
    x=x_new
else:
    print("fail jacobi method ...")
    exit(1)
x
  

array([ 0.99997362, -0.99997086,  1.99992916, -1.99995087,  2.99990705,
       -2.99994638,  3.99991441, -3.99995895,  4.99994905, -4.99998467])

In [75]:
print("the sol of ax = b using Jacobi method is \n{}".format(x))
print("indeed ax-b is \n{}".format(a @x -b))

the sol of ax = b using Jacobi method is 
[ 0.99997362 -0.99997086  1.99992916 -1.99995087  2.99990705 -2.99994638
  3.99991441 -3.99995895  4.99994905 -4.99998467]
indeed ax-b is 
[ -7.36207272e-05  -4.87551647e-05  -1.97659494e-04  -8.19269659e-05
  -2.59256556e-04  -8.90011829e-05  -2.38630852e-04  -6.78503510e-05
  -1.42001948e-04  -2.52706070e-05]


In [82]:
import sympy as sy
sy_mat_a=sy.Matrix(a)
sy_x=sy_mat_a.solve(b)
sy_x-x

Matrix([
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0]])

In [67]:
for i in range(5):
    if i >2:
        break
else:
    print("hoge")

# final code is

In [84]:
n=10
a=np.diag([5.]*n)
a+=np.diagflat([2.]*(n-1),1)
a+=np.diagflat([2.]*(n-1),-1)
print(a)

b=np.array([3,1,4,0,5,-1,6,-2,7,-15],dtype='f').T
#initial value x
x=np.ones(10).T

D=np.diag(np.diag(a))
L=np.tril(a,-1)
U=np.triu(a,+1)

invD=np.linalg.inv(D)

epsilon=0.0001
maxiteration=100

for k in range(maxiteration):
    x_new=invD @ (b-(L+U) @ x)
    if(np.linalg.norm(x_new-x) <epsilon):
        break
    x=x_new
else:
    print("fail jacobi method ...")
    exit(1)
x

print("the sol of ax = b using Jacobi method is \n{}".format(x))
print("indeed ax-b is \n{}".format(a @x -b))
print("you can check sol x using sympy...")
import sympy as sy
sy_mat_a=sy.Matrix(a)
sy_x=sy_mat_a.solve(b)
print(sy_x)
  

[[ 5.  2.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  5.  2.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  2.  5.  2.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  2.  5.  2.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  5.  2.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  2.  5.  2.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  2.  5.  2.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  2.  5.  2.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  2.  5.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  2.  5.]]
the sol of ax = b using Jacobi method is 
[ 0.99997362 -0.99997086  1.99992916 -1.99995087  2.99990705 -2.99994638
  3.99991441 -3.99995895  4.99994905 -4.99998467]
indeed ax-b is 
[ -7.36207272e-05  -4.87551647e-05  -1.97659494e-04  -8.19269659e-05
  -2.59256556e-04  -8.90011829e-05  -2.38630852e-04  -6.78503510e-05
  -1.42001948e-04  -2.52706070e-05]
you can check sol x using sympy...
Matrix([[1.00000000000000], [-1.00000000000000], [2.00000000000000], [-2.00000000000000], [3.00000000000000], [-3.00000000000000], [4.00000000000000], [-4.00000000000000], [5.0000