In [1]:
import numpy as np

# solve linear equation $ax=b$ using LU decomposite

In [2]:
a=np.matrix([[2,4,6],
                        [1,-1,5],
                        [4,1,-2]],dtype='float64')
b=np.matrix([28,7,21],'float64').T
x=np.array([[None]*3],dtype='float64').T
print(x)
swap_array=np.array([[None]*3]).T
print(swap_array)

[[ nan]
 [ nan]
 [ nan]]
[[None]
 [None]
 [None]]


In [3]:
(row,col)=a.shape
for j in range(row):
    #search pivot
    maxind=j+np.argmax(abs(a[j:,j]))
    swap_array[j]=maxind
    #swap!
    a[[j,maxind],j:]=a[[maxind,j],j:]
    pivot=a[j,j]
    for i in range(j+1,row):
        p=- a[i,j] /pivot
        a[i,j:]+=p*a[j,j:]
        #memorize value p
        a[i,j]=p
print(a)
print(swap_array)

[[ 4.          1.         -2.        ]
 [-0.25        3.5         7.        ]
 [-0.5         0.35714286  8.        ]]
[[2]
 [2]
 [2]]


In [4]:
a=np.matrix([[4,1,-2],
                        [-1/4,7/2,7],
                        [-1/2,5/14,8]],dtype='float64')
b=np.matrix([28,7,21],'float64').T
swap=np.array([2,2,2])

In [5]:
#swap b
j=0
b[[swap[j],j]]=b[[j,swap[j]]]

for i in range(j+1,row):
    print(a[i,j],b[j])
    b[i]=b[i] + a[i,j] * b[j]
b

-0.25 [[ 21.]]
-0.5 [[ 21.]]


matrix([[ 21.  ],
        [  1.75],
        [ 17.5 ]])

In [6]:
j=1
b[[swap[j],j]]=b[[j,swap[j]]]
for i in range(j+1,row):
    print(a[i,j],b[j])
    b[i]=b[i] + a[i,j] * b[j]
b

0.357142857143 [[ 17.5]]


matrix([[ 21. ],
        [ 17.5],
        [  8. ]])

# push-forward

In [7]:

a=np.matrix([[4,1,-2],
                        [-1/4,7/2,7],
                        [-1/2,5/14,8]],dtype='float64')
b=np.matrix([28,7,21],'float64').T
swap=np.array([2,2,2])

for j in range(row):
    b[[swap[j],j]]=b[[j,swap[j]]]
    for i in range(j+1,row):
        b[i]+= a[i,j] * b[j]
b

matrix([[ 21. ],
        [ 17.5],
        [  8. ]])

# back-foward

In [8]:
#backforward
for i in range(row)[::-1]:
    x[i]=(b[i]-np.dot(a[i,i+1:row],x[i+1:row]))/a[i,i]
x

array([[ 5.],
       [ 3.],
       [ 1.]])

#final result

In [9]:
a=np.matrix([[4,1,-2],
                        [0,7/2,7],
                        [0,0,8]],dtype='float64')
b=np.matrix([[ 21. ],
                        [ 17.5],
                        [  8. ]])
x=np.matrix([None]*3,dtype='float64').T
#for check sum
ori_a=a
#define extended coefficient matrix of eq ax=b
a=np.concatenate([a,b],axis=1)
#push forward
(row,col)=a.shape
for j in range(row):
    #search pivot
    maxind=np.argmax(abs(a[j:,j]))+j
    #swap!
    a[[j,maxind],:]=a[[maxind,j],:]
    for i in range(j+1,row):
        p= -a[i,j] /a[j,j]
        a[i]+=p*a[j]
print('extended coefficient matrix applied gauss method \n a={}'.format(a))
#back forward
for i in range(row)[::-1]:
    x[i]=(a[i,col-1]-np.dot(a[i,i+1:row],x[i+1:row]))/a[i,i]
print('x={}'.format(x))

extended coefficient matrix applied gauss method 
 a=[[  4.    1.   -2.   21. ]
 [  0.    3.5   7.   17.5]
 [  0.    0.    8.    8. ]]
x=[[ 5.]
 [ 3.]
 [ 1.]]


# confirm calclation flow

# final code

In [10]:
a=np.matrix([[2,4,6],
                        [1,-1,5],
                        [4,1,-2]],dtype='float64')
b=np.matrix([28,7,21],'float64').T
x=np.array([[None]*3],dtype='float64').T
swap_array=np.array([[None]*3]).T
(row,col)=a.shape

for j in range(row):
    #search pivot
    maxind=j+np.argmax(abs(a[j:,j]))
    swap_array[j]=maxind
    #swap!
    a[[j,maxind],j:]=a[[maxind,j],j:]
    pivot=a[j,j]
    for i in range(j+1,row):
        p=- a[i,j] /pivot
        a[i,j:]+=p*a[j,j:]
        #memorize value p at [i,j]
        a[i,j]=p
        
for j in range(row):
    b[[swap[j],j]]=b[[j,swap[j]]]
    for i in range(j+1,row):
        b[i]+= a[i,j] * b[j]
#backforward
for i in range(row)[::-1]:
    x[i]=(b[i]-np.dot(a[i,i+1:row],x[i+1:row]))/a[i,i]
x

array([[ 5.],
       [ 3.],
       [ 1.]])